# require your app file first
require './app'
require 'sinatra/activerecord/rake'
require 'active_record'
require 'yaml'


namespace :db  do


  desc "Create Database"

  task :create do
    config = DatabaseTasks.settings
    DatabaseTasks.new(config).create_database
  end



  task :migrate do
    config = DatabaseTasks.settings
    DatabaseTasks.new(config).migrate
  end

  task :drop do
    config = DatabaseTasks.settings
    DatabaseTasks.new(config).drop_database
  end

end